### ISSUE TITLE
Finding out what is tested?

### ISSUE THREAD

**Issue by russel** [Zipios/Zipios#13]
On Debian Sid I see the test result:
```
zipios_tests[26439]: version 2.1.4, seed is 1488212785
===============================================================================
All tests passed (3880256 assertions in 31 test cases)
```
whereas on Fedora Rawhide, I see:
```
zipios_tests[4783]: version 2.1.4, seed is 1488213923
===============================================================================
All tests passed (2169585 assertions in 31 test cases)
```
So same number of test cases, very different number of assertions. Is there any way of discovering why the number of assertions is so disparate?

**Comment by AlexisWilke** [comment]
I have various entries that use `rand()` to size a for loop which means the number of items will vary.

If you rerun the tests multiple times, the number of assertions changes each time (assuming you rerun at least within 1 second, as I use `time()` to see the `rand()` system.)

            uint32_t size(rand() % 100 + 20);
            for(uint32_t i(0); i < size; ++i)
            {
                b.push_back(rand());
            }

This allows our tests to fail in circumstances that would not otherwise happen. Long run, it should never fail, but if it does and the `rand()` function is involved, we can use the `--seed 123` to re-test with the exact same sequence of `rand()` functions. This is also why I print out the seed on the first line.

**Comment by AlexisWilke** [comment]
Now it is interesting that it all passes. Did you do some tweaking for the I/O errors that were not generated earlier?

**Comment by russel** [comment]
I fixed the lambda expressions, commented out the SIGSEGV, and it all worked. So the nullptr problem is all that we have left for a release that works on GCC 6 and 7 on Debian and Fedora.

I am looking into setting up a Travis-CI test, but it will likely be GCC 4.9 because Travis-CI uses an ancient Ubuntu.

**Comment by russel** [comment]
I think my original question is answered so I am closing this issue. If there are other points from this thread let's create new issues for them.

**Comment by AlexisWilke** [comment]
I am not so sure that GCC 4.9 will work since we use C++11. It was still under development around that time...
