### ISSUE TITLE
-std=c++11 overrides GCC 7 default of c++14

### ISSUE THREAD

**Issue by hobbes1069** [Zipios/Zipios#6]
https://gcc.gnu.org/projects/cxx-status.html#cxx14

With the current cmake configuration I must resort to brute force to remove the setting of "-std=c++11" 

If I have time I'll see if there's a way to handle this automatically. I see in the cmake configuration output that the C++ compiler's capabilities are checked which hopefully sets a variable we can use.

**Comment by russel** [comment]
This became a real problem for Gtkmm, if I remember correctly, due to this sort of configuration situation in a dependency. The result was that Gtkmm and the dependencies do not now specify a C++ version but leave it that if a environment doesn't have a good enough compiler compilation errors ensue. This seems a bit awkward. However given that CMake and GCC/Clang do not allow to say "C++11 or later", treating this as a build system problem does seem like the best way forward.

If this is an acceptable position for us, then I propose removing the C++11 structure and suffer moans from people using pre C++11 compilers. Unless I have missed a way forward…

**Comment by hobbes1069** [comment]
I found the property "CMAKE_CXX_STANDARD_COMPUTED_DEFAULT" that's set after compiler detection. I was playing with it to see if I could setup something like (pseudo-code):

```
if CMAKE_CXX_STANDARD_COMPUTED_DEFAULT >= 11
    don't add -std=c++11
else
    set CMAKE_CXX_STANDARD_REQUIRED 11
endif
```

And let cmake take care of it rather than explicitly adding "-std=c++11"

What about the cygwin case? Does it really need the gnu extensions?

**Comment by AlexisWilke** [comment]
Ubuntu 16.04 is still on C++99 (or was it 98?) and thus C++11 has to be forced on that OS. Since it is still the current LTS, I think we should do our best to keep that default for now, unless a better version is available by default (as mentioned in g++ 7.0+) So @hobbes1069 solution would be best, assuming we get that same variable in older versions of cmake (or if not defined, force C++11...)

**Comment by russel** [comment]
Others, include LLVM, have had this problem. I'll have a play based on @hobbes1069 proposal.

**Comment by dooglio** [comment]
What we should look into is making use of:
[target_compile_features](https://cmake.org/cmake/help/v3.1/command/target_compile_features.html#command:target_compile_features)
[C++ known features](https://cmake.org/cmake/help/v3.1/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES)

Here the manual describes how to use the feature enforcer: 
[cmake-compile-features](https://cmake.org/cmake/help/v3.1/manual/cmake-compile-features.7.html#manual:cmake-compile-features(7))

The above insures that the appropriate switch is set for the appropriate compiler, and is a great way to insure cross-platform support.

So the idea is that you select the feature you want, and what is really awesome is that you can tell the compiler if the feature is required publicly.

So if we want to support, say, C++ lambdas, it would look like this:
```
add_library( mylib my_file.cpp )
target_compile_features( mylib PRIVATE cxx_lambdas )
```

However, you could link against `mylib` without having that feature turned on in your local compiler.

**Comment by hobbes1069** [comment]
A little bit of issue necro here... Anyone have any fresh thoughts on this?

**Comment by AlexisWilke** [comment]
At this time, we still need to compile under 16.04. Once that is gone we could remove the option as the default in newer systems is at least C++11.

**Comment by hobbes1069** [comment]
There may be a way to test through CMake at this point but I found this code snippet that could be executed:

```
$ g++ -x c++  -E -dM -< /dev/null | grep __cplusplus
#define __cplusplus 201402L
```

Do the default for my gcc is C++14.

Per StackOverflow this could be compared to:

```
199711 for C++98,
201103 for C++11
201402 for C++14
201703 for C++17
```

So in CMake pseudo code something like:
```
try_compile (above code and extract cplusplus macro)
if ( cplusplus_macro < 201103 )
    <add -std flag>
endif ()
```

**Comment by AlexisWilke** [comment]
At this time, we still need to compile under 16.04. Once that is gone we could remove the option as the default in newer systems is at least C++11. I suppose I could also look into what version of cmake Ubuntu 16.04 has and test against that. If that old, then add the stdc++11 as you mentioned. I don't know that testing the C++ compiler is a good idea.

**Comment by RokerHRO** [comment]
Isn't it possible to set the C++ version to "C++11 or newer if that is the default C++ version"?

**Comment by AlexisWilke** [comment]
This is done as I mentioned above. I'm done with 16.04 (obviously?!) and the current version forces gnu++17 for Cygwin, but otherwise, it should use your current compiler. You can still force a compiler by setting `CMAKE_CXX_FLAGS` on cmake's command line (`cmake -DCMAKE_CXX_FLAGS=-std=gnu++23 ...`).
