### ISSUE TITLE
Use of catch.hpp

### ISSUE THREAD

**Issue by russel** [Zipios/Zipios#9]
Currently we assume anyone running the tests has an instance of catch.hpp in the contrib directory. Should we either copy this in and version it or create a submodule to capture it?

**Comment by AlexisWilke** [comment]
In the tests/CMakeLists.txt, I see a `find_package()` call:

    find_package( Catch )

If you have catch installed, then it will detect it, otherwise it will just not build the tests.

The `FindCatch.cmake` is under the `cmake` directory. Unfortunately, at this point the catch packages do not come with a `FindCatch.cmake` file so we have to provide our own.

If you do place a `catch.hpp` under `contrib`, the current version of `FindCatch.cmake` will find it, but we do not include a version of `catch.hpp` in our repository...

Although what we could try is invert the search order. The current order looks like this:

    FIND_PATH(CATCH_INCLUDE_DIR
      catch.hpp
      PATHS
        ${CMAKE_SOURCE_DIR}/contrib
        /usr/local/include
        /usr/include
    )

That being said, if someone wants to use a newer version than what their OS offers, the current order offers the capability to install `catch.hpp` in their `contrib` folder and it will pick that one up, overriding the default OS version.

So to my point of view it is already done the correct way.

**Comment by russel** [comment]
OK, seems like the status quo is the correct situation.
